excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - SwiftLint-Example/AppDelegate.swift


# Disable Rules
disabled_rules:
  - todo
  - trailing_whitespace


# Max line length
line_length: 130


# Max function body
function_body_length: 5


# Max - Min
file_length:
  warning: 20
  error: 50


# Function parameter count
function_parameter_count:
  warning: 2
  error: 3


# Nested complex code
cyclomatic_complexity:
- 2 # warning
- 3 # error


# Custom Rule
# ex: let example = 0
custom_rules:
  
  # Specific name - key ... regex
  id_suffix_naming:
    name: "Wrong name"
    regex: "(example)"
    match_kinds:
      - comment
      - identifier
    message: "Use 'Example' instead 'eXample'"
    severity: error

  # Force ssl protocol
  # ex: let apiUrl = "http://github.com"
  force_https:
     name: "Force HTTPS over HTTP"
     regex: "((?i))http(?!s)"
     match_kinds: string
     message: "HTTPS should be used instead of HTTP"
     severity: warning

  # Capitalize first word in comment 
  # ex: // swiftlint:disable empty_count
  comments_capitalized_ignore_possible_code:
    name: "Capitalize First Word In Comment"
    regex: "(^ +// +(?!swiftlint)[a-z]+)"
    message: "The first word of a comment should be capitalized"
    severity: warning


# Mark indentation
# ex: // MARK : -
invalid_mark_format:
    name: "Invalid MARK Format"
    regex: '(?m-s)(\/\/[\s]*?MARK(?!(\:[\s]{1}\-[\s]{1}){1}))'
    message: "Use format: MARK: - Your Info"
    severity: warning


# Variable Name lowercase letter
# ex: let Deneme = "API_KEY"
lowercase_constants:
    name: "Lowercase Constants"
    regex: '[ \t]let[ \t]*[A-Z][\w]*[ \t]*(=|:)'
    message: "Constants should begin with a lowercase character."
    severity: warning
    match_kinds:
      - argument
      - comment.mark
      - comment.url
      - identifier
      - typeidentifier